version: '3.8'

services:
  web:
    build: .
    container_name: rehan_crm
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
