# Generated by Django 4.2 on 2024-08-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_client_nextofkin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[("Land", "Land"), ("Building", "Building")],
                        max_length=255,
                    ),
                ),
                ("loction", models.CharField(max_length=255)),
                ("total_units", models.IntegerField(default=1)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=100)),
                ("image", models.ImageField(null=True, upload_to="property_images/")),
                (
                    "title_deed",
                    models.FileField(null=True, upload_to="property_title_deeds/"),
                ),
                ("sold_out", models.BooleanField(default=False)),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "deposit_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyPaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("payment_period", models.IntegerField(default=1)),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "deposit_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("unit_number", models.CharField(max_length=255)),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "deposit_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "unit_status",
                    models.CharField(
                        choices=[
                            ("Booked", "Booked"),
                            ("Reserved", "Reserved"),
                            ("Sold", "Sold"),
                            ("Available", "Available"),
                        ],
                        default="Available",
                        max_length=255,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.client",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propertyunits",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
