# Generated by Django 4.2 on 2024-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="county",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="town",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
