# Generated by Django 4.2 on 2024-08-22 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_property_county_property_town"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="loction",
            new_name="location",
        ),
    ]
