# Generated by Django 4.2 on 2024-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_rename_loction_property_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyunit",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
