# Generated by Django 4.2 on 2024-08-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_client_acquired_by"),
        ("properties", "0004_propertyunit_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientunits",
                to="users.client",
            ),
        ),
    ]
