# Generated by Django 4.2 on 2024-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpaymentplan",
            name="fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
