# Generated by Django 4.2 on 2024-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_clientpaymentplan_fully_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinstallment",
            name="date_expected",
            field=models.DateField(null=True),
        ),
    ]
