# Generated by Django 4.2 on 2024-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_clientinstallment_date_expected"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpaymentplan",
            name="first_repayment_date",
            field=models.DateField(null=True),
        ),
    ]
