# Generated by Django 4.2 on 2024-08-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_client_nextofkin"),
        ("finance", "0004_clientpaymentplan_first_repayment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinstallment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.client"
            ),
        ),
    ]
