# Generated by Django 4.2 on 2024-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_clientinstallment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinstallment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Defaulted", "Defaulted"),
                    ("Future", "Future"),
                ],
                default="Future",
                max_length=255,
            ),
        ),
    ]
