# Generated by Django 4.2 on 2024-08-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_client_nextofkin"),
        ("finance", "0006_clientinstallment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinstallment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clienstallments",
                to="users.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientinstallment",
            name="payment_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planinstallments",
                to="finance.clientpaymentplan",
            ),
        ),
    ]
