# Generated by Django 4.2 on 2024-08-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_client_nextofkin"),
        ("finance", "0007_alter_clientinstallment_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpaymentplan",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientpaymentplans",
                to="users.client",
            ),
        ),
    ]
