# Generated by Django 4.2 on 2024-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_clientpayment_recorded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpayment",
            name="payment_reason",
            field=models.CharField(
                choices=[
                    ("Deposit", "Deposit"),
                    ("Booking", "Booking"),
                    ("Installment", "Installment"),
                    ("Combined", "Combined"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
