# Generated by Django 4.2 on 2024-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_clientpayment_date_paid_clientpayment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="date_paid",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="clientpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Mpesa", "Mpesa"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Bank Deposit", "Bank Deposit"),
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="clientpayment",
            name="payment_reason",
            field=models.CharField(
                choices=[
                    ("Deposit", "Deposit"),
                    ("Booking", "Booking"),
                    ("Installment", "Installment"),
                    ("Combined", "Combined"),
                ],
                max_length=255,
            ),
        ),
    ]
