# Generated by Django 4.2 on 2024-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_visitor_checkout_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
